version: '3.8'

services:
  agrogest-notifications:
    image: fabrizioleonardoramirez/agrogest-notifications:latest
    container_name: agrogest-notifications-service
    ports:
      - "8085:8085"
    environment:
      - SPRING_DATASOURCE_URL=jdbc:postgresql://ep-misty-cloud-adzqdacj-pooler.c-2.us-east-1.aws.neon.tech/neondb?sslmode=require
      - SPRING_DATASOURCE_USERNAME=neondb_owner
      - SPRING_DATASOURCE_PASSWORD=npg_b1lrVD2jFmsX
      - KAFKA_BOOTSTRAP_SERVERS=agrogest-kafka:29092
    networks:
      - red-zookeeper
      - red-kafka

networks:
  red-zookeeper:
    external: true
    name: agrogest-zookeeper-network
  red-kafka:
    external: true
    name: agrogest-kafka-network